#!/bin/sh

echo "Checking if this device is supported..."
UNAME_OUTPUT=`uname -a`
if [[ "$UNAME_OUTPUT" == *"arm64"* ]]
then
	echo "This device is supported."
	exit 0
fi

echo -e "\nThis device is not supported, sorry... Dolphin requires an iOS device with a 64-bit processor."
exit 1
